#iterations of tasks until the condition fails

# for (i=0; i<5; i++) {
# }

# a= [apple, mango, banana]
# #  for i in len(a):
# #    print('Fruit Name' + a[i])

#loop


- name: Loop Demo
  hosts: localhost
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item }}"
      loop:
        - apple
        - banana
        - orange

    - name: Print Fruits with Quantity
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item.name }}, Quantity - {{ item.quantity }}"
      loop:
        - { name: apple , quantity: 10 }
        - { name: banana , quantity: 20 }
        - { name: orange , quantity: 30 }      