apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: app-1  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-bookworm-perl
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "0.5 GB"
              cpu: "0.25 vCPU"
            limits:
              memory: "0.5 GB"
              cpu: "0.25 vCPU"    

---

apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: nginx
  namespace: app-1 
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30007
  type: LoadBalancer    

